import type { Colors } from "./ColorVariants";

// Helper function to convert camelCase to kebab-case
const camelToKebab = (str: string): string => {
  return str.replace(/([a-z0-9]|(?=[A-Z]))([A-Z])/g, "$1-$2").toLowerCase();
};

// Helper function to create color class maps
const createColorMap = (prefix: "text" | "bg" | "border"): Record<Colors, string> => {
  const colorVariants: Colors[] = [
    "white",
    "qonto",
    "primary",
    "primary-25",
    "primary-50",
    "primary-100",
    "primary-200",
    "primary-300",
    "primary-400",
    "primary-500",
    "primary-600",
    "primary-700",
    "primary-800",
    "primary-900",
    "success",
    "success-50",
    "success-100",
    "success-200",
    "success-300",
    "success-400",
    "success-500",
    "success-600",
    "success-700",
    "success-800",
    "success-900",
    "secondary",
    "secondary-25",
    "secondary-50",
    "secondary-100",
    "secondary-200",
    "secondary-300",
    "secondary-400",
    "secondary-500",
    "secondary-600",
    "secondary-700",
    "secondary-800",
    "secondary-900",
    "interactive",
    "interactive-50",
    "interactive-100",
    "interactive-200",
    "interactive-300",
    "interactive-400",
    "interactive-500",
    "interactive-600",
    "interactive-700",
    "interactive-800",
    "interactive-900",
    "info",
    "info-50",
    "info-100",
    "info-200",
    "info-300",
    "info-400",
    "info-500",
    "info-600",
    "info-700",
    "info-800",
    "info-900",
    "danger",
    "danger-50",
    "danger-100",
    "danger-200",
    "danger-300",
    "danger-400",
    "danger-500",
    "danger-600",
    "danger-700",
    "danger-800",
    "danger-900",
    "warning",
    "warning-50",
    "warning-100",
    "warning-200",
    "warning-300",
    "warning-400",
    "warning-500",
    "warning-600",
    "warning-700",
    "warning-800",
    "warning-900",
    "purple",
    "purple-50",
    "purple-100",
    "purple-200",
    "purple-300",
    "purple-400",
    "purple-500",
    "purple-600",
    "purple-700",
    "purple-800",
    "purple-900",
    "automation",
    "automation-50",
    "automation-100",
    "automation-200",
    "automation-300",
    "automation-400",
    "automation-500",
    "automation-600",
    "automation-700",
    "automation-800",
    "automation-900",
    "automation-gradient-background",
    "automation-gradient-badge-indicator",
    "automation-gradient-icon-bg",
    "brandBeige",
    "brandFlashGreen",
    "brandDeepBlue",
    "plan-basic",
    "plan-essential",
    "plan-premium",
    "decorativeBlueLighter",
    "decorativeOrangeLighter",
    "decorativeVioletLighter",
    "decorativeYellowLighter",
    "decorativeGreenLighter",
    "decorativePinkLighter",
    "decorativeCyanLighter",
    "decorativeBrownLighter",
    "decorativeBlueSoft",
    "decorativeOrangeSoft",
    "decorativeVioletSoft",
    "decorativeYellowSoft",
    "decorativeGreenSoft",
    "decorativePinkSoft",
    "decorativeCyanSoft",
    "decorativeBrownSoft",
    "decorativeBlueMid",
    "decorativeOrangeMid",
    "decorativeVioletMid",
    "decorativeYellowMid",
    "decorativeGreenMid",
    "decorativePinkMid",
    "decorativeCyanMid",
    "decorativeBrownMid",
    "decorativeBlueDarker",
    "decorativeOrangeDarker",
    "decorativeVioletDarker",
    "decorativeYellowDarker",
    "decorativeGreenDarker",
    "decorativePinkDarker",
    "decorativeCyanDarker",
    "decorativeBrownDarker",
  ];

  const map: Record<string, string> = {};
  colorVariants.forEach((color) => {
    const kebabColor = camelToKebab(color);
    map[color] = `${prefix}-${kebabColor}`;
  });

  return map as Record<Colors, string>;
};

export const textColorMap = createColorMap("text");
export const bgColorMap = createColorMap("bg");
export const borderColorMap = createColorMap("border");
export const hoverBgColorMap = createColorMap("hover:bg");
export const hoverBorderColorMap = createColorMap("hover:border");

